<?php 
// namespace Accounting;

class BackendExploratoryCest
{
    public function _before(AcceptanceTester $I)
    {
    }

    // tests
    public function backendExploratory(\Step\Acceptance\AllSteps $I)
    {
    	$I->loginAsAdmin();
    	$I->click('WP ERP');
            $I->waitForElementVisible('#wpbody-content', 30);
            $I->checkError();
                $I->see('Overview');
                $I->see('Latest Announcement');
                $I->see('HR');
                $I->see('CRM');
                $I->see('Accounting');
                $I->see('Latest ERP Blog');
    	$I->click('HR');
            $I->waitForElementVisible('.erp-single-container', 30);
            $I->checkError();
                $I->see('HR Management');
                $I->see('Latest Announcement');
                $I->see('My Leave Calendar');
                $I->see('Birthday Buddies');
                $I->see('Who is out');
                $I->see('About to end');
            // $I->click('Employees');
            $I->amOnPage('/wp-admin/admin.php?page=erp-hr&section=employee');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Employees');
            $I->amOnPage('/wp-admin/admin.php?page=erp-hr&section=department');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Departments');
            $I->amOnPage('/wp-admin/admin.php?page=erp-hr&section=designation');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Designation');
            $I->amOnPage('/wp-admin/edit.php?post_type=erp_hr_announcement');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Announcement');
            $I->amOnPage('/wp-admin/admin.php?page=erp-hr&section=leave');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Leave Requests');
            $I->amOnPage('/wp-admin/admin.php?page=erp-hr&section=report');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Reports');
            $I->amOnPage('/wp-admin/admin.php?page=erp-hr&section=help');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('HRM Help');
    	$I->click('CRM');
            $I->waitForElementVisible('.erp-single-container', 30);
            $I->checkError();
                $I->see('CRM Dashboard');
                $I->see('My Schedules');
                $I->see('Customer Statistics');
                $I->see("Today's Schedules");
                $I->see('Upcoming Schedules');
                $I->see('Recently Added');
                $I->see('Total Inbound Emails');
            $I->amOnPage('/wp-admin/admin.php?page=erp-crm&section=contacts');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Contact');
            $I->amOnPage('/wp-admin/admin.php?page=erp-crm&section=companies');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Company');
            $I->amOnPage('/wp-admin/admin.php?page=erp-crm&section=activities');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Activities');
            $I->amOnPage('/wp-admin/admin.php?page=erp-crm&section=schedules');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Schedules');
                $I->click('All Schedules');
            $I->amOnPage('/wp-admin/admin.php?page=erp-crm&section=contact-groups');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Contact Groups');
            $I->amOnPage('/wp-admin/admin.php?page=erp-crm&section=reports');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('Reports');
            $I->amOnPage('/wp-admin/admin.php?page=erp-crm&section=help');
                $I->waitForElementVisible('#wpbody', 30);
                $I->checkError();
                $I->see('CRM Help');
    	$I->click('Accounting');
            $I->waitForElementVisible('#erp-accounting', 30);
            $I->checkError();
                $I->see('Dashboard');
                $I->see('Income & Expense');
                $I->see('Accounts');
                $I->see('Invoice payable to you');
                $I->see('Bills you need to pay');
            $I->amOnPage('/wp-admin/admin.php?page=erp-accounting#/users');
                $I->waitForElementVisible('.app-customers', 30);
                $I->checkError();
                $I->see('Customers');
            $I->amOnPage('/wp-admin/admin.php?page=erp-accounting#/transactions');
                $I->waitForElementVisible('.wperp-container', 30);
                $I->checkError();
                $I->see('Sales Transactions');
            $I->amOnPage('/wp-admin/admin.php?page=erp-accounting#/charts');
                $I->waitForElementVisible('#erp-accounting', 30);
                $I->checkError();
                $I->see('Chart of Accounts');
            $I->amOnPage('/wp-admin/admin.php?page=erp-accounting#/banks');
                $I->waitForElementVisible('#erp-accounting', 30);
                $I->checkError();
                $I->see('Accounts');
            $I->amOnPage('/wp-admin/admin.php?page=erp-accounting#/products');
                $I->waitForElementVisible('.wperp-products', 30);
                $I->checkError();
                $I->see('Products');
            $I->amOnPage('/wp-admin/admin.php?page=erp-accounting#/taxes');
                $I->waitForElementVisible('.app-taxes', 30);
                $I->checkError();
                $I->see('Tax Rates');
            $I->amOnPage('/wp-admin/admin.php?page=erp-accounting#/reports');
                $I->waitForElementVisible('.reports-overview', 30);
                $I->checkError();
                $I->see('Trial Balance');
                $I->see('Ledger Report');
                $I->see('Income Statement');
                $I->see('Sales Tax');
                $I->see('Balance Sheet');
            $I->amOnPage('/wp-admin/admin.php?page=erp-accounting#/erp-ac-help');
                $I->waitForElementVisible('#erp-accounting', 30);
                $I->checkError();
                $I->see('Accounting Help');
    	$I->click('Company');
            $I->waitForElementVisible('#wpbody-content', 30);
            $I->checkError();
    	$I->click('Tools');
            $I->waitForElementVisible('.postbox', 30);
            $I->checkError();
            // $I->see('Admin Menu');
            //     $I->click('Import');
            //         $I->waitForElementVisible('.postbox', 30);
            //     $I->click('Export');
            //         $I->waitForElementVisible('.postbox', 30);
            //     $I->click('Misc.');
            //         $I->waitForElementVisible('.postbox', 30);
            //     $I->click('Status');
            //         $I->waitForElementVisible('.postbox', 30);
            //     $I->click('Audit Log');
            //         $I->waitForElementVisible('.postbox', 30);
    	$I->click('Modules');
            $I->waitForElementVisible('#wpbody-content', 30);
            $I->checkError();
            $I->see('Modules');
    	$I->click('Add-Ons');
            $I->waitForElementVisible('#wpbody-content', 30);
            $I->checkError();
            $I->see('Add-ons');
    	$I->click('Settings');
            $I->waitForElementVisible('#mainform', 30);
            $I->checkError();
            // $I->see('General Options');
            //     $I->click('Emails');
            //         $I->waitForElementVisible('#mainform', 30);
            //     $I->click('HR');
            //         $I->waitForElementVisible('#mainform', 30);
            //     $I->click('Contact Forms');
            //         $I->waitForElementVisible('#mainform', 30);
            //     $I->click('CRM');
            //         $I->waitForElementVisible('#mainform', 30);
            //     $I->click('Accounting');
            //         $I->waitForElementVisible('#mainform', 30);
    }
}
